version: '3.8'

services:
  postgres_test:
    image: postgres:13
    env_file:
      - ./test.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Expose on host port 5433 to avoid conflict with dev db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

  api_test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./test.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      # Include other necessary environment variables for the API if any
      # For example, if Keycloak is used in tests or needs to be mocked:
      # KEYCLOAK_SERVER_URL: http://keycloak:8080/auth/
      # KEYCLOAK_REALM: myrealm
      # KEYCLOAK_API_CLIENT_ID: myclient
      # KEYCLOAK_API_CLIENT_SECRET: mysecret
      # KEYCLOAK_REDIRECT_URI: http://localhost:5000/callback
    depends_on:
      - postgres_test
    ports:
      - "5001:80" # Expose on host port 5001 to avoid conflict with dev api
    restart: unless-stopped

volumes:
  postgres_test_data:
    driver: local
