"""create workflow and task tables for postgresql

Revision ID: initial
Revises: 
Create Date: 2025-05-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from app.db_models.enums import WorkflowStatus, TaskStatus

# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_names', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum(WorkflowStatus), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_id'), 'workflow_instances', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_definition_id'), 'workflow_instances', ['workflow_definition_id'], unique=False)
    
    op.create_table('task_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum(TaskStatus), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_id'), 'task_instances', ['id'], unique=False)
    op.create_index(op.f('ix_task_instances_workflow_instance_id'), 'task_instances', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_instances_workflow_instance_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_workflow_instances_workflow_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
