"""add_due_datetime_fields

Revision ID: 5ed86f33ce5c
Revises: 447f84f38a7e
Create Date: 2025-06-04 06:20:58.683053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed86f33ce5c'
down_revision = '447f84f38a7e' # Ensure this is the correct previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definitions', sa.Column('due_datetime_offset_minutes', sa.Integer(), nullable=True, server_default=sa.text('0')))
    op.add_column('task_instances', sa.Column('due_datetime', sa.DateTime(), nullable=True))
    op.add_column('workflow_definitions', sa.Column('due_datetime', sa.DateTime(), nullable=True))
    op.add_column('workflow_instances', sa.Column('due_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_instances', 'due_datetime')
    op.drop_column('workflow_definitions', 'due_datetime')
    op.drop_column('task_instances', 'due_datetime')
    op.drop_column('task_definitions', 'due_datetime_offset_minutes')
    # ### end Alembic commands ###
