"""change_workflow_instance_created_at_to_datetime

Revision ID: 64348a0ef10f
Revises: 5ed86f33ce5c
Create Date: 2024-07-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64348a0ef10f'
down_revision: Union[str, None] = '5ed86f33ce5c' # Using the ID alembic generated
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_instances', 'created_at',
               existing_type=sa.Date(),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###
