version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - keycloak
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
